### ISSUE TITLE
Create cloudformation templates to create the environments

### ISSUE THREAD

**Issue by christopherhein** [christopherhein/aws-container-migration-workshop#25]
Single Account ; multiple environments use Cloud9

**Comment by omarlari** [comment]
notes:
cloud9 - install kops, kubectl (copy from aws-kubernetes-workshop)
rds t2.micro instance
subnet group for ^^
ecr repo

**Comment by christopherhein** [comment]
I think the one difference between the k8s workshop and this is we should auto create the `kops` cluster, right?

**Comment by christopherhein** [comment]
We also need to get access to the scripts that Luke created.

**Comment by omarlari** [comment]
errr... i want to have a requirement for bring your own account. A few drawbacks I saw to Lukes approach was responsibility for the Isengard accounts, and getting folks credentials at the begining was a pain. We can get them credits, I will put Torres on the hunt for that.
