### ISSUE TITLE
Create Initial Deck

### ISSUE THREAD

**Issue by christopherhein** [christopherhein/aws-container-migration-workshop#8]
Would be **awesome** if we can use something that is easily version controlled so we can easily edit it. But if all else fails we can just use PowerPoint.

**Goals:**
- [x] Expected Outcome: How to diagnose at a high-level what a good candidate for a container migration and categorize it
- [x] Expected Outcome: Basic understanding of discovery tools
- [x] Expected Outcome: Concepts of cloud-native architectures
- [x] Expected Outcome: Containers vs Serverless
- [ ] Expected Outcome: Culture Modernization. Also, cover: Containerize before migrating to AWS or after?
- [ ] Expected Outcome: Things to care post-migration
- [ ] “Optimize” the container cluster - Security, networking, monitoring

**Comment by mandusm** [comment]
Find the Deck Here: https://onlyoffice.lab.cloudsamurai.io/products/files/doceditor.aspx?fileid=20
